### ISSUE TITLE
Missing Texture Error (java.io.FileNotFoundException)

### ISSUE THREAD

**Issue by XxCoolGamesxX** [ExtraCells/ExtraCells2#178]
Hey,
Not use the Optifine and not use a Resource Pack. Only of Minecraft
Use: EXTRACELLS-2.2.55B85.
Forge: 10.13.2.1291

Here error:

```
[17:44:04] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/items/MISSING_ICON_ITEM_4646_extracells.fluid.item.png
java.io.FileNotFoundException: minecraft:textures/items/MISSING_ICON_ITEM_4646_extracells.fluid.item.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
    at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:303) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

```
[20:27:44] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/MISSING_ICON_BLOCK_939_extracells.block.walrus.png
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_939_extracells.block.walrus.png
    at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
    at shadersmodcore.client.ShadersTex.loadResource(ShadersTex.java:998) ~[ShadersTex.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:125) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) [bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) [bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) [bqf.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
    at com.mumfrey.liteloader.client.GameEngineClient.refreshResources(GameEngineClient.java:62) [GameEngineClient.class:1.7.10_04]
    at com.mumfrey.liteloader.client.ClientEvents.onStartupComplete(ClientEvents.java:236) [ClientEvents.class:1.7.10_04]
    at com.mumfrey.liteloader.client.CallbackProxyClient.onStartupComplete(CallbackProxyClient.java:48) [CallbackProxyClient.class:1.7.10_04]
    at com.mumfrey.liteloader.core.event.EventProxy.$event00000(EventProxy.java:211) [EventProxy.class:1.7.10_04]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:573) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by DrummerMC** [comment]
You can ignorthis error

**Comment by XxCoolGamesxX** [comment]
Are you plan to fix error of the missing texture?

**Comment by Nedelosk** [comment]
Fixed
