### ISSUE TITLE
Right-clicking fluid terminal with container causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by amcoder** [ExtraCells/ExtraCells2#197]
Right-clicking on the fluid terminal with a container in my hand causes an IndexOutOfBoundsException to be thrown.

This happens with TE strongboxes, as well as EU drums. The game does not crash with a vanilla chest, though the animation happens as if the chest is being placed on the terminal, however it does not actually get placed.

I'm using ExtraCells version 2.2.68bNIGHTLY from Curse.

```
[00:49:48] [Client thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ClientTickEvent@e1b5e35:
java.lang.IndexOutOfBoundsException: Index: 40, Size: 38
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_25]
    at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_25]
    at net.minecraft.inventory.Container.func_75144_a(SourceFile:206) ~[zs.class:?]
    at extracells.container.ContainerFluidTerminal.func_75144_a(ContainerFluidTerminal.java:175) ~[ContainerFluidTerminal.class:?]
    at invtweaks.forge.ClientProxy.slotClick(ClientProxy.java:94) ~[ClientProxy.class:?]
    at invtweaks.InvTweaksContainerManager.click(InvTweaksContainerManager.java:266) ~[InvTweaksContainerManager.class:?]
    at invtweaks.InvTweaksContainerManager.leftClick(InvTweaksContainerManager.java:253) ~[InvTweaksContainerManager.class:?]
    at invtweaks.InvTweaksContainerManager.move(InvTweaksContainerManager.java:147) ~[InvTweaksContainerManager.class:?]
    at invtweaks.InvTweaksContainerSectionManager.move(InvTweaksContainerSectionManager.java:41) ~[InvTweaksContainerSectionManager.class:?]
    at invtweaks.InvTweaksHandlerAutoRefill$1.run(InvTweaksHandlerAutoRefill.java:195) ~[InvTweaksHandlerAutoRefill$1.class:?]
    at invtweaks.InvTweaks$1.run(InvTweaks.java:122) ~[InvTweaks$1.class:?]
    at invtweaks.InvTweaks.onTick(InvTweaks.java:479) ~[InvTweaks.class:?]
    at invtweaks.InvTweaks.onTickInGUI(InvTweaks.java:151) ~[InvTweaks.class:?]
    at invtweaks.forge.ForgeClientTick.onTick(ForgeClientTick.java:22) ~[ForgeClientTick.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_421_ForgeClientTick_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1576) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by DrummerMC** [comment]
Can you try to disable inventory tweaks

**Comment by amcoder** [comment]
Removing Inventory Tweaks fixes the crash, though it does still attempt the place the item in front of the terminal. For example, right-clicking with a bucket of water actually places a water source block. Updating inventory tweaks doesn't fix the problem either. I also tried the latest ExtraCells release from this morning (2.2.69) and it won't even load.

However, this is in ME^4, and forge and most of the mods are outdated.

I also did some testing on a clean MultiMC instance with only:
Forge 10.13.3.1370
AE2 rv2 beta 28
Inventory Tweaks 1.59 dev 152
Code Chicken Core 1.0.4.35
NEI 1.0.4.95
ExtraCells 2.2.69

Everything seems to work perfectly in that instance. There is no crash, and right-clicking on the fluid terminal doesn't try to place the block in my hand. This is probably related to something specific about the versions of everything in ME^4.

Let me know if you need me to do anything else with this.

**Comment by PRAVEEN1984ETW** [comment]
RE
