### ISSUE TITLE
Fluid interface does not store state during backup

### ISSUE THREAD

**Issue by nrllewellyn** [ExtraCells/ExtraCells2#205]
By default, the AromaBackup mod runs on startup. During this first backup, the fluid interface fails to write its state, producing this stack trace:

[12:38:03] [AromaBackup/ERROR] [FML]: A TileEntity type extracells.tileentity.TileEntityFluidInterface has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
        at extracells.tileentity.TileEntityFluidInterface.getGridNode(TileEntityFluidInterface.java:387) ~[TileEntityFluidInterface.class:?]
        at extracells.tileentity.TileEntityFluidInterface.writeToNBTWithoutExport(TileEntityFluidInterface.java:1083) ~[TileEntityFluidInterface.class:?]
        at extracells.tileentity.TileEntityFluidInterface.func_145841_b(TileEntityFluidInterface.java:1068) ~[TileEntityFluidInterface.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunakLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.command.server.CommandSaveAll.func_71515_b(SourceFile:36) [bh.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at aroma1997.backup.ThreadBackup.run(ThreadBackup.java:34) [ThreadBackup.class:?]

This also causes problems with the Fluid Interfaces, as they all are in a broken state once the world starts (any ME cables are disconnected). The work-around for this is to break and replace any affected interfaces every time the server restarts.

**Comment by ruifung** [comment]
Does this still happen?
