### ISSUE TITLE
Server crash using ME Ore Dictionary Bus

### ISSUE THREAD

**Issue by railstar0083** [ExtraCells/ExtraCells2#207]
EXTRACELLS-1.7.10-2.2.48B74

I installed an ME Ore Dictionary Export Bus and the server came down,

Log paste of the crash from my end.  I will try to request the server logs.

[07:32:32] [Server Connector #4/ERROR]: Couldn't connect to server
java.net.ConnectException: Connection refused: no further information: /108.170.33.141:25565
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.7.0_75]
    at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.7.0_75]
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:191) ~[NioSocketChannel.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:228) ~[AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:497) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) ~[?:1.7.0_75]
[07:32:40] [Client thread/INFO]: Connecting to 108.170.33.141, 25565
[07:32:41] [Server Connector #5/ERROR]: Couldn't connect to server
java.net.ConnectException: Connection refused: no further information: /108.170.33.141:25565
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.7.0_75]
    at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.7.0_75]
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:191) ~[NioSocketChannel.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:228) ~[AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:497) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) ~[?:1.7.0_75]

**Comment by RAnders00** [comment]
@railstar0083 it's been 6 days since you posted the issue, any updates since then?
