### ISSUE TITLE
Fluid Assembler Crash

### ISSUE THREAD

**Issue by SGStino** [ExtraCells/ExtraCells2#239]
I managed the get extra cells crashing by inserting a crafting recipe into an interface next to the fluid assembler.

I had no idea how it works, so i decided to try just like the normal assembler to place a fluid assembler surrounded with fluid interfaces.

Then i added a normal recipe pattern for Heavy Cream into the interface, and it instantly crashed.
If i restart the server, it crashes again.

```
java.lang.NullPointerException
    at appeng.me.cache.CraftingGridCache.updatePatterns(CraftingGridCache.java:279) ~[CraftingGridCache.class:?]
    at appeng.me.cache.CraftingGridCache.addNode(CraftingGridCache.java:235) ~[CraftingGridCache.class:?]
    at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:55) ~[GridCacheWrapper.class:?]
    at appeng.me.Grid.add(Grid.java:205) ~[Grid.class:?]
    at appeng.me.GridNode.setGrid(GridNode.java:255) ~[GridNode.class:?]
    at appeng.me.Grid.<init>(Grid.java:71) ~[Grid.class:?]
    at appeng.me.GridNode.getInternalGrid(GridNode.java:150) ~[GridNode.class:?]
    at appeng.me.GridNode.updateState(GridNode.java:217) ~[GridNode.class:?]
    at extracells.part.PartECBase.addToWorld(PartECBase.java:80) ~[PartECBase.class:?]
    at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605) ~[CableBusContainer.class:?]
    at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221) ~[TileCableBus.class:?]
    at appeng.hooks.TickHandler.onTick(TickHandler.java:231) ~[TickHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_707_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Extracells jar in use: EXTRACELLS-1.7.10-2.2.70B119 from resonant rise modpack.

**Comment by Sir-Will** [comment]
@ruifung any news to this, I have an similar crash issue. I also can't remove the block as I have no idea at which location.

```
java.lang.NullPointerException: Exception in server tick loop
    at appeng.me.cache.CraftingGridCache.updatePatterns(CraftingGridCache.java:279)
    at appeng.me.cache.CraftingGridCache.addNode(CraftingGridCache.java:235)
    at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:55)
    at appeng.me.Grid.add(Grid.java:205)
    at appeng.me.GridNode.setGrid(GridNode.java:256)
    at appeng.me.Grid.<init>(Grid.java:71)
    at appeng.me.GridNode.getInternalGrid(GridNode.java:151)
    at appeng.me.GridConnection.<init>(GridConnection.java:91)
    at appeng.me.GridNode.FindConnections(GridNode.java:453)
    at appeng.me.GridNode.updateState(GridNode.java:217)
    at extracells.tileentity.TileEntityFluidCrafter.getGridNode(TileEntityFluidCrafter.java:213)
    at appeng.me.GridNode.FindConnections(GridNode.java:406)
    at appeng.me.GridNode.updateState(GridNode.java:217)
    at extracells.tileentity.TileEntityFluidInterface.getGridNode(TileEntityFluidInterface.java:387)
    at appeng.me.GridNode.FindConnections(GridNode.java:406)
    at appeng.me.GridNode.updateState(GridNode.java:217)
    at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
    at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
    at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
    at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
    at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_520_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by XFactHD** [comment]
@SirWilli your crash report is incomplete. Please put the complete crash report on pastebin.com and post the link here.

**Comment by Sir-Will** [comment]
It doesn't include any required informaton but here:
http://pastebin.com/5jRS0nBh

**Comment by XFactHD** [comment]
If you know in which dimension you built this and what shape it has, you can open your world in MCEdit. The camera will be the view of the player and by selecting a block you can get the block name. If you find the fluid interface or the fluid crafter, just delete it and you should be good to go.

**Comment by Sir-Will** [comment]
I know, but as I said I have no idea about the location and the worlds are huge.

**Comment by XFactHD** [comment]
Did it crash right after you put the pattern into the interface? If that's the case the camera will be directly in front of the offending block.

**Comment by Sir-Will** [comment]
It wasn't me it was a other player where I don't know which player and I also don't know what exactly he/she did.

**Comment by XFactHD** [comment]
You could switch through all player cameras (I know that this is rough). As the crash reason is an exception in the tick loop it must have happened as soon as the pattern was placed in the interface.

**Comment by GuardianDragonlord** [comment]
i try to make the Fluid interface to have it auto craft fill bucket with block to make it by have a Fluid interface add to a molecular assembler and interring a encoded crash hit

http://pastebin.com/dHAVmQsL

**Comment by PhoenixtheII** [comment]
+1 having this issue in FTB Infinity Expert 2.4.2

**Comment by Tydesson** [comment]
Hi,

Just had the bug with Inifinity "normal" 2.4.2.
A player was using the Fluid Interface with a pattern when it crashed.

http://pastebin.com/RPjpj38J

**Comment by spannerman79** [comment]
> having this issue in FTB Infinity Expert 2.4.2
> 
> Just had the bug with Inifinity "normal" 2.4.2.

@PhoenixtheII & @Tydesson - don't blame the mod author when a modpack that you are running is on an old build.  Take your complaints to the modpack author/s

http://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2292902

**Comment by Tydesson** [comment]
Did i blame somebody ? No, i just posted a crash report, to help somebody debug something
You are not happy ? http://i.imgur.com/e2bsF55.gif

**Comment by spannerman79** [comment]
1) You are running a third party modpack.  It is common knowledge when there is an issue you take the issue to the modpack author, not the mod dev.  It is people like you that make modders throw their hands up and say stuff it cause people like you are too idiotic to actually check with the modpack author/s themselves first.  In fact there are even some mod author conditions that the author deals with issues first before accepting them on their issue tracker.

2)  You are running an old pack version.

3)   Really?  That really shows your level of immaturity.

**Comment by Tydesson** [comment]
http://i.imgur.com/e2bsF55.gif

**Comment by ensirius** [comment]
fuck you ExtraCells2 devs. Found a lot dupes/bugs/crashes with your shity mod.

**Comment by xvolution** [comment]
It is the mod author's responsibility to tell us when a bug is fixed, not a pack author's. It doesn't matter how old a version of a mod in a pack is. If the ticket is still open, then technically it is still an issue in the current version so having the latest version wouldn't fix it anyways.

Back on topic, we get this issue in the latest version of Infinity Skyblock [1.10.0], which uses ExtraCells 2.3.9b188.

**Comment by Tydesson** [comment]
Finally, words of wisdom !
And a modpack update i have to do :)
