### ISSUE TITLE
Fluid Terminal SMP crash

### ISSUE THREAD

**Issue by juniorjunior** [ExtraCells/ExtraCells2#242]
Right clicking on a fluid terminal in SMP crashes the server.

http://pastebin.com/Kb2a9L5N

Seems to work fine in 73b130.

**Comment by webmilio** [comment]
Still does it in 132.

Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
    at extracells.part.PartFluidTerminal.sendCurrentFluid(PartFluidTerminal.java:278)
    at extracells.part.PartFluidTerminal.sendCurrentFluid(PartFluidTerminal.java:271)
    at extracells.part.PartFluidTerminal.addContainer(PartFluidTerminal.java:68)
    at extracells.container.ContainerFluidTerminal.<init>(ContainerFluidTerminal.java:49)
    at extracells.part.PartFluidTerminal.getServerGuiElement(PartFluidTerminal.java:168)
    at extracells.network.GuiHandler$.getPartContainer(GuiHandler.scala:58)
    at extracells.network.GuiHandler$.getServerGuiElement(GuiHandler.scala:126)
    at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
    at extracells.network.GuiHandler$.launchGui(GuiHandler.scala:71)
    at extracells.network.GuiHandler.launchGui(GuiHandler.scala)
    at extracells.part.PartECBase.onActivate(PartECBase.java:294)
    at extracells.part.PartFluidTerminal.onActivate(PartFluidTerminal.java:179)
    at appeng.parts.CableBusContainer.activate(CableBusContainer.java:803)
    at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:432)
    at appeng.block.AEBaseBlock.func_149727_a(AEBaseBlock.java:549)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 28 more

**Comment by juniorjunior** [comment]
Can we get an update on this? The bug has been present for (at least) close to a month. It makes the mod almost totally unusable.

**Comment by DrummerMC** [comment]
Use the Version on course Not the Version on the build server
