### ISSUE TITLE
NPE While writing NBT in Fluid Interface

### ISSUE THREAD

**Issue by angelnc1989** [ExtraCells/ExtraCells2#259]
![2015-07-18_09 20 02](https://cloud.githubusercontent.com/assets/5382585/8760811/40505976-2d31-11e5-8b06-60b1a99dce4a.png)
This happens on every server restart. I have to break the Interface and place it back down

**Comment by Optimoos** [comment]
If I were to make a guess, I'd say it's a tileentity registration problem. I've been seeing this error on my server:

[11:40:49] [AromaBackup/ERROR] [FML/AromaBackup]: A TileEntity type extracells.tileentity.TileEntityFluidInterface has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
    at extracells.tileentity.TileEntityFluidInterface.getGridNode(TileEntityFluidInterface.java:387) ~[TileEntityFluidInterface.class:?]
    at extracells.tileentity.TileEntityFluidInterface.writeToNBTWithoutExport(TileEntityFluidInterface.java:1083) ~[TileEntityFluidInterface.class:?]
    at extracells.tileentity.TileEntityFluidInterface.func_145841_b(TileEntityFluidInterface.java:1068) ~[TileEntityFluidInterface.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
    at aroma1997.backup.ThreadBackup.save(ThreadBackup.java:191) [ThreadBackup.class:?]
    at aroma1997.backup.ThreadBackup.run(ThreadBackup.java:63) [ThreadBackup.class:?]
[11:40:49] [AromaBackup/ERROR] [FML/AromaBackup]: A TileEntity type extracells.tileentity.TileEntityFluidCrafter has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException
    at extracells.tileentity.TileEntityFluidCrafter.getGridNode(TileEntityFluidCrafter.java:213) ~[TileEntityFluidCrafter.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.getGridNode(TileEntityFluidCrafter.java:203) ~[TileEntityFluidCrafter.class:?]
    at extracells.tileentity.TileEntityFluidCrafter.func_145841_b(TileEntityFluidCrafter.java:496) ~[TileEntityFluidCrafter.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
    at aroma1997.backup.ThreadBackup.save(ThreadBackup.java:191) [ThreadBackup.class:?]
    at aroma1997.backup.ThreadBackup.run(ThreadBackup.java:63) [ThreadBackup.class:?]

**Comment by ruifung** [comment]
Thanks for the log.
