### ISSUE TITLE
Mekanism gas import bus crash

### ISSUE THREAD

**Issue by HoldenMatheson** [ExtraCells/ExtraCells2#266]
Gas Import Bus hooked to a elec sep from mekanism will crash out the second there is any gas to extract with the following log output:

[14:49:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking GridNode
    at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:133) ~[TickManagerCache.class:?]
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
    at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
    at appeng.hooks.TickHandler.onTick(TickHandler.java:238) ~[TickHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_366_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from an unregistered fluid
    at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:41) ~[FluidStack.class:?]
    at extracells.util.GasUtil.getFluidStack(GasUtil.java:137) ~[GasUtil.class:?]
    at extracells.part.PartGasImport.fillToNetwork(PartGasImport.scala:86) ~[PartGasImport.class:?]
    at extracells.part.PartGasImport.doWork(PartGasImport.scala:60) ~[PartGasImport.class:?]
    at extracells.part.PartFluidIO.tickingRequest(PartFluidIO.java:253) ~[PartFluidIO.class:?]
    at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:92) ~[TickManagerCache.class:?]
    ... 11 more
[14:49:07] [Server thread/ERROR]: This crash report has been saved to: D:\Downloads\Devco\minecraft\crash-reports\crash-2015-08-05_14.49.07-server.txt

**Comment by DrummerMC** [comment]
hopfully fixed with https://github.com/ExtraCells/ExtraCells2/commit/7accd33461b623d34d081adbbf5dcb33356ae379
