### ISSUE TITLE
server crash when opening fluid terminal

### ISSUE THREAD

**Issue by adamsonich** [ExtraCells/ExtraCells2#371]
---- Minecraft Crash Report ----
// Oops.

Time: 27.01.16 23:11
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
    at extracells.part.PartFluidTerminal.sendCurrentFluid(PartFluidTerminal.java:278)
    at extracells.part.PartFluidTerminal.sendCurrentFluid(PartFluidTerminal.java:271)
    at extracells.part.PartFluidTerminal.addContainer(PartFluidTerminal.java:68)
    at extracells.container.ContainerFluidTerminal.<init>(ContainerFluidTerminal.java:49)
    at extracells.part.PartFluidTerminal.getServerGuiElement(PartFluidTerminal.java:168)
    at extracells.network.GuiHandler$.getPartContainer(GuiHandler.scala:58)
    at extracells.network.GuiHandler$.getServerGuiElement(GuiHandler.scala:126)
    at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
    at extracells.network.GuiHandler$.launchGui(GuiHandler.scala:71)
    at extracells.network.GuiHandler.launchGui(GuiHandler.scala)
    at extracells.part.PartECBase.onActivate(PartECBase.java:294)
    at extracells.part.PartFluidTerminal.onActivate(PartFluidTerminal.java:179)
    at appeng.parts.CableBusContainer.activate(CableBusContainer.java:803)
    at appeng.block.networking.BlockCableBus.onActivated(BlockCableBus.java:432)
    at appeng.block.AEBaseBlock.func_149727_a(AEBaseBlock.java:549)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 28 more
Caused by: java.lang.NullPointerException

**Comment by DrummerMC** [comment]
try the newest version from the build server

**Comment by adamsonich** [comment]
I will try

**Comment by Nedelosk** [comment]
Fixed in 1.10.
