### ISSUE TITLE
Crash with Practical Logistics 

### ISSUE THREAD

**Issue by d3nisimus** [ExtraCells/ExtraCells2#409]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/4/16 6:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: extracells/item/ItemStoragePhysical
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: extracells/item/ItemStoragePhysical
    at extracells.proxy.CommonProxy.registerItems(CommonProxy.java:56)
    at extracells.Extracells$.preInit(Extracells.scala:88)
    at extracells.Extracells.preInit(Extracells.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: extracells.item.ItemStoragePhysical
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 50 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 54 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 371854440 bytes (354 MB) / 648019968 bytes (618 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCH Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCH appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCH appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCH bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
    UCE extracells{2.3.14} [Extra Cells 2](ExtraCells-1.7.10-2.3.14b197.jar) 
    UCH intellie{2.1.4.573} [IntelliE](IntelligentEnergistics-1.7.10-2.1.4.573-universal.jar) 
    UCH appaero{2.1.4.573} [AppliedAerodynamics](IntelligentEnergistics-1.7.10-2.1.4.573-universal.jar) 
    UE  SonarCore{1.1.3} [SonarCore](SonarCore-1.7.10-1.1.3.jar) 
    UE  PracticalLogistics{0.2.4} [Practical Logistics](Practical-Logistics-1.7.10-0.2.4.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    List of loaded APIs: 
        \* appliedenergistics2|API (rv3) from appliedenergistics2-rv3-beta-6.jar
        \* CoFHAPI (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|block (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|core (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|energy (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|fluid (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|inventory (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|item (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|tileentity (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* CoFHAPI|transport (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
        \* IC2API (1.0) from SonarCore-1.7.10-1.1.3.jar
        \* PracticalLogisticsAPI (1.4) from Practical-Logistics-1.7.10-0.2.4.jar

**Comment by bookerthegeek** [comment]
Please put that up on pastebin.com and put the link here.

How did this happen?
