### ISSUE TITLE
Client crash opening a Fluid Interface

### ISSUE THREAD

**Issue by Eufranio** [ExtraCells/ExtraCells2#412]
Every time i try to open a Fluid Interface, me and my players get that client crash:

```
`---- Minecraft Crash Report ----
// Why did you do that?

Time: 14/07/16 19:36
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.client.gui.Gui.func_94065_a(SourceFile:117)
    at extracells.gui.widget.WidgetFluidTank.draw(WidgetFluidTank.java:60)
    at extracells.gui.GuiFluidInterface.func_146979_b(GuiFluidInterface.java:74)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.client.gui.Gui.func_94065_a(SourceFile:117)
    at extracells.gui.widget.WidgetFluidTank.draw(WidgetFluidTank.java:60)
    at extracells.gui.GuiFluidInterface.func_146979_b(GuiFluidInterface.java:74)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)

-- Screen render details --
Details:
    Screen name: extracells.gui.GuiFluidInterface
    Mouse location: Scaled: (360, 196). Absolute: (720, 393)
    Screen size: Scaled: (720, 393). Absolute: (1440, 785). Scale factor of 2`
```

**Comment by Nedelosk** [comment]
Fixed in 1.10.
