### ISSUE TITLE
ExtraCells-1.10.2-2.4.2aNIGHTLY server crash

### ISSUE THREAD

**Issue by Cracks777** [ExtraCells/ExtraCells2#465]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  PlusTiC (plustic-5.2.1.2.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  DummyPlugin (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  BCModPlugin (backpacks 1.10.2 - 3.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.118.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/4/17 6:20 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (Mekanism)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class extracells.util.UniversalTerminal$
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$1.apply$mcVI$sp(RecipeUniversalTerminal.scala:42)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:30)
	at mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1366)
	at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:368)
	at mekanism.common.integration.OreDictManager.init(OreDictManager.java:40)
	at mekanism.common.Mekanism.postInit(Mekanism.java:1424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

**Comment by Liiw** [comment]
This happened to me as well. As the log would indicate, it is an incompatibility with Mekanism. Hopefully this will be fixed soon!

**Comment by Miner94** [comment]
im having no problem so far

**Comment by Miner94** [comment]
BUt im gunna try all gasses in mekanism and see which if any will cause a crash

**Comment by DrummerMC** [comment]
Can you send me your full log

**Comment by Cracks777** [comment]
[crash-2017-11-04_18.20.43-server.txt](https://github.com/ExtraCells/ExtraCells2/files/1443689/crash-2017-11-04_18.20.43-server.txt)

server wont even start when i put the mod in.

**Comment by DrummerMC** [comment]
set "enablewct" to false in the extracells config or update Wirelass Crafting Terminal

**Comment by Cracks777** [comment]
thank you.
