### ISSUE TITLE
[1.10.2] Fluid Interface Crash

### ISSUE THREAD

**Issue by SanAndreaP** [ExtraCells/ExtraCells2#491]
ExtraCells v. 2.4.2a6
AE v. 2 rv4-stable-1
Forge v. 12.18.3.2511

I placed down the fluid interface on the back of an aqueous accumulator (from Thermal Expansion) whose back is setup to auto-export. I opened the Interface GUI and after like a second I crashed with a NullPointerException:
```
java.lang.NullPointerException: Ticking block entity
	at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:166)
	at extracells.tileentity.TileEntityFluidInterface.tick(TileEntityFluidInterface.java:693)
	at extracells.tileentity.TileEntityFluidInterface.func_73660_a(TileEntityFluidInterface.java:737)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

I had it connected to my main storage network like:
Fluid Interface -> Main AE network -> P2P -> P2P Network -> P2P -> Main AE Network -> Storage Bus on a regular ME Interface connected to the Storage Network -> P2P -> P2P Network -> P2P -> Storage Network -> ME Drives with 20x 64k fluid cells

Here's the full log (warning: quite big):
https://gist.github.com/SanAndreasP/9635699f0d582a20f1846e12dda9a575

**Comment by SanAndreaP** [comment]
Update: After I've made a second storage sub-network just with fluid cells and connecting it via fluid-interface + fluid storage bus combo to the main AE network, it doesn't crash anymore and works properly now.

**Comment by p455w0rd** [comment]
@DrummerMC wrong milestone..AE2 RV4 is 1.10.2
