### ISSUE TITLE
opening fluid assembler crashes my game

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#589]
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:432)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:82)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1731)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ruifung** [comment]
Please add the following details:
Forge version, EC2 version, AE2 version
