### ISSUE TITLE
[1.12.2] Loader Exception Mod Crash

### ISSUE THREAD

**Issue by kokkie20** [ExtraCells/ExtraCells2#613]
`Time: 10/28/18 9:19 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Cells 2 (extracells)
Caused by: java.lang.ExceptionInInitializerError
	at extracells.proxy.CommonProxy.registerItems(CommonProxy.java:93)
	at extracells.ExtraCells.preInit(ExtraCells.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:105)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at com.google.common.reflect.TypeResolver$TypeMappingIntrospector.visitClass(TypeResolver.java:357)
	at com.google.common.reflect.TypeVisitor.visit(TypeVisitor.java:80)
	at com.google.common.reflect.TypeResolver$TypeMappingIntrospector.getTypeMappings(TypeResolver.java:350)
	at com.google.common.reflect.TypeResolver.accordingTo(TypeResolver.java:64)
	at com.google.common.reflect.TypeToken.resolveType(TypeToken.java:249)
	at com.google.common.reflect.TypeToken.<init>(TypeToken.java:149)
	at net.minecraftforge.registries.IForgeRegistryEntry$Impl$1.<init>(IForgeRegistryEntry.java:64)
	at net.minecraftforge.registries.IForgeRegistryEntry$Impl.<init>(IForgeRegistryEntry.java:64)
	at net.minecraft.item.Item.<init>(Item.java:169)
	at extracells.item.ItemECBase.<init>(ItemECBase.java:10)
	at extracells.item.storage.ItemStorageCellPhysical.<init>(ItemStorageCellPhysical.java:66)
	at extracells.registries.ItemEnum.<clinit>(ItemEnum.java:22)
	... 42 more`

I am getting this error, do you have any idea what could be wrong? Is it a FML thing or is it a EC2 issue?
Just updated FML due to a mod requiring a update but as soon as i did that EC2 pops up with this error :(

**Comment by BrockWS** [comment]
Please specify what version of Forge/AE2/EC2 you are using.

**Comment by kokkie20** [comment]
Sorry my bad, should have known to include that stuff but was kinda in a rush when i posted this
Information requested:
Forge: 14.23.5.2768
AE2: Rv6 Stable 3
EC2: 1.12.2 2.6.1

**Comment by BrockWS** [comment]
Unable to reproduce. Please try disabling mods one at a time to see if that fixes it.

**Comment by ruifung** [comment]
Judging by that stack trace, I'd say it's probably some mod that bundled the AE API or something like that.

Also, I think instead of posting just the stack trace, you should post the entire crash report because that also contains the mod list too.

**Comment by jefferyrlc** [comment]
similar crash here
Forge: 14.23.5.2772
AE2: rv5-stable-11
EC2: 1.12.2 2.6.1

Crash Report:
[crash-2018-12-02_20.07.37-client.txt](https://github.com/ExtraCells/ExtraCells2/files/2637681/crash-2018-12-02_20.07.37-client.txt)

**Comment by ruifung** [comment]
@jefferyrlc In your case, you have mismatched AE2 and EC2 versions. EC2 2.6.1 is for AE2 RV6
