### ISSUE TITLE
Part Gas Export Error or ? Pls fixed fast my Server still down. #bug #crashserver

### ISSUE THREAD

**Issue by Midnight-Vortex** [ExtraCells/ExtraCells2#614]
`java.lang.IncompatibleClassChangeError: Interface method reference: appeng.api.parts.IPart.getCapability(Lnet/minecraftforge/common/capabilities/Capability;)Ljava/lang/Object;, is in an indirect superinterface of extracells.part.gas.PartGa
	at extracells.part.gas.PartGasExport.getCapability(PartGasExport.scala:96)
	at appeng.tile.networking.TileCableBus.getCapability(TileCableBus.java:407)
	at crazypants.enderio.base.power.forge.ForgeAdapter.getCapability(ForgeAdapter.java:54)
	at crazypants.enderio.base.power.forge.ForgeAdapter.getPowerInterface(ForgeAdapter.java:43)
	at crazypants.enderio.base.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:25)
	at crazypants.enderio.conduits.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:505)
	at crazypants.enderio.conduits.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:454)
	at crazypants.enderio.conduits.conduit.AbstractConduit.updateConnections(AbstractConduit.java:429)
	at crazypants.enderio.conduits.conduit.AbstractConduit.updateEntity(AbstractConduit.java:400)
	at crazypants.enderio.conduits.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:339)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:47)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by ruifung** [comment]
Please provide the following:
1. AE2 version
2. EC2 version

**Comment by p455w0rd** [comment]
as @BrockWS has pointed out in my discord in the #mc_code_learning channel, this appears to be an error on Scala's end (referenced ![here](https://github.com/scala/scala-dev/issues/143)). It has been fixed, but Forge is currently shipping with an obsolete version of Scala.

**Comment by ruifung** [comment]
I'm curious, how old is the version of scala bundled with forge? Scala 2.12 has been around for like 2 years or so now..

**Comment by p455w0rd** [comment]
forge ships with 2.11

**Comment by Midnight-Vortex** [comment]
forge 1.12.2 - 14.23.5.2768
AE- appliedenergistics2-rv6-stable-3
EC2 - ExtraCells-1.12.2-2.6.1a

**Comment by zaekeon** [comment]
I had my server crash when I stuck the gas export bus on a nuclearcraft fusion controller

**Comment by BrockWS** [comment]
EC2 will be updated soon to fix this but in the meantime you should be able to use this to fix the crash.
https://ci.brock.pw/job/ExtraCells2/job/BrockWS/10/artifact/build/libs/ExtraCells-1.12.2-2.6.2a10.jar
(Let me know if that doesn't work)
