### ISSUE TITLE
Crafting recipe for storage.fluid.portable error. 

### ISSUE THREAD

**Issue by Vivigar** [ExtraCells/ExtraCells2#689]
```
[Server thread/ERROR] [FML]: Parsing error loading recipe extracells:storagecells/fluid/portable
com.google.gson.JsonParseException: Missing data for item 'extracells:storage.fluid.portable'
        at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:217) ~[CraftingHelper.class:?]
        at net.minecraftforge.oredict.ShapelessOreRecipe.factory(ShapelessOreRecipe.java:157) ~[ShapelessOreRecipe.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$919/1057442811.parse(Unknown Source) ~[?:?]
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) [CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$930/1071790782.apply(Unknown Source) [CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) [CraftingHelper.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$928/1291466589.accept(Unknown Source) [CraftingHelper.class:?]
        at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_51]
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by Danekjovax** [comment]
More information about this error would greatly help.

**Comment by Shad0wlife** [comment]
Looking at the commit history, this should be fixed with #685 . But there's no build out with that so you'd have to ~~build it~~ edit the corresponding assets yourself. You can see what needs to be changed in that commit.
