### ISSUE TITLE
ExtraCells2 v. 2.6.5 | MC 1.12.2 | ME Drive Fixture Lights Render Bug

### ISSUE THREAD

**Issue by ArcCharger96** [ExtraCells/ExtraCells2#690]
As title ME Drive Fixture has some visual bugs when storage cell are inside.
First thing, when storage cells are "shift+right clicked" inside or manually "drag+click" sometimes it doesn't render outside (like that http://prntscr.com/razsqh ---> http://prntscr.com/razsfn);
Second, when storage cells are full (space/byte used or item types) they should turn red or orange, instead this is what happens http://prntscr.com/razvd2 (storage cell view http://prntscr.com/razw8o).

Someone pointed out that this issue is caused by wrong coordinates https://github.com/ExtraCells/ExtraCells2/issues/683 (and possible solution?)

Using last ExtraCells2 version on PO3 pack, I'll wait for an answer, cross finger this could be easly fixed :)

**Comment by Shad0wlife** [comment]
Open the mods jarfile with 7zip or similar software, edit the given value from the issue you linked and see if it works.
The files are in assets/extracells/models/part.

Then you can tell whether that helped :)

**Comment by dannyr-git** [comment]
Here is the CCL exception for this bug :

[16:31:48] [Chunk Batcher 51/INFO]: [CHAT] CCL Caught an exception rendering a block. See the log for info.
[16:32:09] [Chunk Batcher 53/ERROR]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:254, y:14, z:-2295
  Block Class:   class appeng.block.networking.BlockCableBus
  Registry Name: appliedenergistics2:cable_bus
  Metadata:      0
  State:         appliedenergistics2:cable_bus
 Tile at position
  Tile Class:    class appeng.tile.networking.TileCableBus
  Tile Id:       appliedenergistics2:blockcablebus
  Tile NBT:      {"def:3":{id:"extracells:part.base",Count:1b,tag:{inventory:[{Slot:0b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:air",Count:1b,Damage:0s}]},Damage:7s},"def:4":{id:"extracells:part.base",Count:1b,tag:{inventory:[{Slot:0b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:air",Count:1b,Damage:0s}]},Damage:7s},hasRedstone:2,"def:6":{id:"appliedenergistics2:part",Count:1b,Damage:16s},x:254,"extra:4":{inventory:[{Slot:0b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:air",Count:1b,Damage:0s}]},y:14,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},z:-2295,"facade:3":{id:"appliedenergistics2:facade",Count:1b,tag:{damage:0,item:"minecraft:quartz_block"},Damage:0s},id:"appliedenergistics2:blockcablebus","facade:2":{id:"appliedenergistics2:facade",Count:1b,tag:{damage:0,item:"minecraft:quartz_block"},Damage:0s},"extra:3":{inventory:[{Slot:0b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:1b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:2b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:3b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:4b,id:"minecraft:air",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:air",Count:1b,Damage:0s}]},"facade:5":{id:"appliedenergistics2:facade",Count:1b,tag:{damage:0,item:"minecraft:quartz_block"},Damage:0s},"facade:4":{id:"appliedenergistics2:facade",Count:1b,tag:{damage:0,item:"minecraft:quartz_block"},Damage:0s},"extra:6":{}}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(Unknown Source) ~[?:1.8.0_261]
	at java.util.LinkedList.remove(Unknown Source) ~[?:1.8.0_261]
	at extracells.models.drive.PartDriveBakedModel.func_188616_a(PartDriveBakedModel.java:39) ~[PartDriveBakedModel.class:?]
	at appeng.client.render.cablebus.CableBusBakedModel.func_188616_a(CableBusBakedModel.java:131) ~[CableBusBakedModel.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:95) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:61) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 5 more
