### ISSUE TITLE
Client crashes after crafting

### ISSUE THREAD

**Issue by xXPerditorXx** [ExtraCells/ExtraCells2#724]
If I try to create the multi wirless terminal, everything is ok but if i want to craft Wireless Crafting Terminal the CLlient crashed:
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events
Exit Code: -1

Regards

**Comment by 9hax** [comment]
Hi, I came here to second this. 
I'm gonna dump my crashlog here:
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.29.3_Forge_1.12.jar)
  GTCELoadingPlugin (gregtech-1.12.2-1.17.1.770.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  GITDLoadingPlugin (getittogetherdrops-1.12.2-v1.0.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.3.0_Forge_1.12 (2).jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 3/22/23 6:43 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at extracells.item.ItemWirelessTerminalUniversal.isInstalled(ItemWirelessTerminalUniversal.scala:219)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:66)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:65)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:65)
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:92)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:53)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_184098_a(AEBaseGui.java:596)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:671)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.ItemWirelessTerminalUniversal.isInstalled(ItemWirelessTerminalUniversal.scala:219)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:66)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$2.apply(RecipeUniversalTerminal.scala:65)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:65)
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:92)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:53)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_184098_a(AEBaseGui.java:596)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:671)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: appeng.client.gui.implementations.GuiCraftingTerm

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['9hax'/373, l='MpServer', x=-114.71, y=56.00, z=68.27]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-8,64,256), Chunk: (at 8,4,0 in -1,16; contains blocks -16,0,256 to -1,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7913086 game time, 8760550 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntitySheep['Sheep'/448, l='MpServer', x=-121.93, y=64.00, z=81.61], EntityCow['Cow'/449, l='MpServer', x=-123.69, y=64.00, z=80.62], EntitySheep['Sheep'/450, l='MpServer', x=-120.97, y=64.00, z=80.76], EntitySheep['Sheep'/451, l='MpServer', x=-121.93, y=64.00, z=80.13], EntitySheep['Sheep'/452, l='MpServer', x=-120.02, y=64.00, z=80.05], EntityPlayerSP['9hax'/373, l='MpServer', x=-114.71, y=56.00, z=68.27], EntitySheep['Sheep'/453, l='MpServer', x=-119.08, y=64.00, z=80.77], EntitySkeleton['Skeleton'/517, l='MpServer', x=-138.23, y=25.00, z=68.48], EntitySkeleton['Skeleton'/518, l='MpServer', x=-188.50, y=49.00, z=131.50], EntitySkeleton['Skeleton'/519, l='MpServer', x=-185.50, y=49.00, z=130.50], EntitySpider['Spider'/493, l='MpServer', x=-73.50, y=12.00, z=111.50], EntitySheep['Sheep'/432, l='MpServer', x=-120.12, y=64.00, z=82.55], EntitySheep['Sheep'/433, l='MpServer', x=-120.97, y=64.00, z=82.55], EntitySheep['Sheep'/434, l='MpServer', x=-120.00, y=64.00, z=81.62], EntitySheep['Sheep'/435, l='MpServer', x=-121.91, y=64.00, z=82.55], EntityCow['Cow'/436, l='MpServer', x=-124.47, y=64.00, z=81.63], EntitySheep['Sheep'/437, l='MpServer', x=-119.08, y=64.00, z=82.55], EntitySheep['Sheep'/374, l='MpServer', x=-120.02, y=64.00, z=79.07], EntityCow['Cow'/438, l='MpServer', x=-123.08, y=64.00, z=81.52], EntitySheep['Sheep'/375, l='MpServer', x=-121.93, y=64.00, z=79.07], EntityCow['Cow'/439, l='MpServer', x=-124.00, y=64.00, z=82.55], EntityCow['Cow'/376, l='MpServer', x=-125.83, y=64.00, z=81.51], EntityCow['Cow'/440, l='MpServer', x=-125.00, y=64.00, z=82.55], EntitySheep['Sheep'/377, l='MpServer', x=-119.11, y=64.00, z=79.86], EntitySheep['Sheep'/441, l='MpServer', x=-119.08, y=64.00, z=81.66], EntitySheep['Sheep'/378, l='MpServer', x=-120.96, y=64.00, z=79.07], EntityCow['Cow'/442, l='MpServer', x=-126.93, y=64.00, z=82.55], EntityCow['Cow'/379, l='MpServer', x=-126.93, y=64.00, z=81.31], EntityCow['Cow'/443, l='MpServer', x=-125.06, y=64.00, z=80.45], EntityCow['Cow'/444, l='MpServer', x=-123.08, y=64.00, z=82.55], EntitySheep['Sheep'/445, l='MpServer', x=-120.99, y=64.00, z=81.61], EntityCow['Cow'/446, l='MpServer', x=-125.95, y=64.00, z=82.55], EntityCreeper['Creeper'/510, l='MpServer', x=-135.50, y=14.00, z=87.50], EntityCow['Cow'/447, l='MpServer', x=-125.15, y=64.00, z=79.20]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1637597120 bytes (1561 MB) / 4060086272 bytes (3872 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_F5 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                             | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                             | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core                 | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCHIJA | xaeroworldmap_core                | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LCHIJA | openmodscore                      | 0.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore                       | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCHIJA | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | brandonscore                      | 2.4.19                   | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LCHIJA | aenetvistool                      | 1.0.3                    | AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar       | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCHIJA | jei                               | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.27                   | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | enderio                           | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHIJA | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | ae2wtlib                          | 1.0.34                   | AE2WTLib-1.12.2-1.0.34.jar                         | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | amidst-forge                      | 1.12.2-0.6.2             | amidst-forge-1.12.2-0.6.2.jar                      | None                                     |
	| LCHIJA | biomesoplenty                     | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftcompat                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildinggadgets                   | 2.8.4                    | BuildingGadgets-2.8.4.jar                          | None                                     |
	| LCHIJA | rf-capability-adapter             | 1.0                      | capabilityadapter-1.0.1.jar                        | None                                     |
	| LCHIJA | cctweaked                         | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                       | None                                     |
	| LCHIJA | computercraft                     | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                       | None                                     |
	| LCHIJA | clumps                            | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCHIJA | compactmachines3                  | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar            | None                                     |
	| LCHIJA | dazzle                            | 2.0.0                    | dazzle-2.0.0.jar                                   | None                                     |
	| LCHIJA | enderiobase                       | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LCHIJA | energyconverters                  | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar               | None                                     |
	| LCHIJA | energymeters                      | 1.0.2                    | energymeters-1.12.2-1.0.2.jar                      | None                                     |
	| LCHIJA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | extracells                        | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                        | None                                     |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
	| LCHIJA | foamfix                           | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                         | None                                     |
	| LCHIJA | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | getittogetherdrops                | 1.0.2                    | getittogetherdrops-1.12.2-v1.0.2.jar               | None                                     |
	| LCHIJA | gregtech                          | 1.17.1.770               | gregtech-1.12.2-1.17.1.770.jar                     | None                                     |
	| LCHIJA | ichunutil                         | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | ic2                               | 2.8.222-ex112            | industrialcraft-2-2.8.222-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | teslacorelib                      | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | multithreadednoise                | 0.0.2                    | MultithreadedNoise-1.12.2-0.0.2.jar                | None                                     |
	| LCHIJA | nei                               | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | portalgun                         | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | railcraft                         | 12.0.0                   | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | thermaldynamics                   | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCHIJA | immersiveengineering              | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                   | None                                     |
	| LCHIJA | simplyjetpacks                    | 1.12.2-2.2.18.1          | SimplyJetpacks2-1.12.2-2.2.18.1.jar                | None                                     |
	| LCHIJA | tesserakt                         | 1.3                      | tesserakt-1.3.jar                                  | None                                     |
	| LCHIJA | thermalinnovation                 | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| LCHIJA | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | wailaharvestability               | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| LCHIJA | xaerominimap                      | 23.3.0                   | Xaeros_Minimap_23.3.0_Forge_1.12 (2).jar           | None                                     |
	| LCHIJA | xaeroworldmap                     | 1.29.3                   | XaerosWorldMap_1.29.3_Forge_1.12.jar               | None                                     |
	| LCHIJA | teslacorelib_registries           | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
XaeroWorldMapPlugin (XaerosWorldMap_1.29.3_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftTransformer
GTCELoadingPlugin (gregtech-1.12.2-1.17.1.770.jar)
  gregtech.common.asm.GTCETransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
GITDLoadingPlugin (getittogetherdrops-1.12.2-v1.0.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_23.3.0_Forge_1.12 (2).jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.49' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/user/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 528.49, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 528.49
	OpenGlRenderer: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16```
